pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                bat 'dotnet restore'
                bat '"C:\\Users\\ASUS\\AppData\\Roaming\\npm\\playwright" install'
            }
        }
        stage('Run Tests') {
            steps {
                bat 'dotnet test'
            }
        }
    }
    post {
        always {
            publishHTML(target: [
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'PlanitTechnicalAssessment/bin/Debug/net9.0/Reports',
                reportFiles: 'TestReport_*.html',
                reportName: 'Extent Report'
            ])
        }
    }
}