pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'dotnet restore'
                sh 'playwright install'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'dotnet test'
            }
        }
        stage('Generate Allure Report') {
            steps {
                sh 'allure generate allure-results --clean -o allure-report'
            }
        }
    }
    post {
        always {
            allure([
                results: [[path: 'allure-results']]
            ])
        }
    }
}