pipeline {
    agent any
    environment {
        DOTNET_CLI_HOME = "${WORKSPACE}"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                bat 'dotnet --version'
            }
        }
        stage('Install Dependencies') {
            steps {
                bat 'dotnet restore'
            }
        }
        stage('Run Tests') {
            steps {
                bat 'dotnet test'
            }
        }
    }
    post {
        always {
            publishHTML(target: [
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: "${WORKSPACE}/PlanitTechnicalAssessment/bin/Debug/net9.0/Reports",
                reportFiles: 'TestReport_*.html',
                reportName: 'Extent Report'
            ])
        }
        failure {
            echo 'Pipeline failed! Check logs for details.'
        }
        success {
            echo 'Pipeline completed successfully!'
        }
    }
}